name: DavidSmith
favicon: null
layout_spectrum: 0.98662
typography_spectrum: 0.1394389697816223
title: 'Cinematographer - David C. Smith, A Loose Collection of Thoughts and Experiences'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#8b8c87'
    - '#ced6fd'
    - '#222e22'
    - '#595651'
  brandStrength: 0.21984870661981404
  lightness: 0.19357690517790616
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
