name: DavidSmith
favicon: null
layout_spectrum: 0.25845
typography_spectrum: 0.25
title: 'David C. Smith - Cinematographer, A Loose Collection of Thoughts and Experiences'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#8b8c87'
    - '#ced6fd'
    - '#222e22'
    - '#595651'
  brandStrength: 0
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
